
{% set name = "wrftamer" %}
{% set version = "v1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/os-simopt/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1d05dd51f713c79b518f46d214eaf23c304fcaa2055bd569e7c5f02672b9d083

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python~=3.9.0
    - pytest~=6.2.2
    - pandas~=1.3.5
    - setuptools~=52.0.0
    - panel~=0.12.6
    - pyyaml~=6.0
    - numpy~=1.19.2
    - xarray~=0.16.2
    - cartopy~=0.18.0
    - shapely~=1.7.1
    - netcdf4~=1.5.8
    - python-crontab~=2.5.1
    - click~=7.1.2
    - matplotlib
    - holoviews~=1.14.6
    - hvplot~=0.7.3
    - windrose~=1.6.8
    - wrf-python~=1.3.1

#test:
#  imports:
#    - wrftamer

about:
  home: https://github.com/os-simopt/wrftamer
  summary: 'A program that helps you to manage WRF experiments'
  description: |
    WRFtamer is a program to create, manage and plot WRF projects and experiments.
  licence: MIT
  licence_family: MIT
  licence_file:
    - LICENCE
    - LICENCES.third_party
  doc_url: https://wrftamer.readthedocs.io/
  dev_url: https://github.com/os-simopt/wrftamer

extra:
  recipe-maintainers:
    - 99740179
