{% set name = 'wrftamer' %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  path: ./

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - click
    - holoviews
    - hvplot
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas >=1.3.5
    - panel
    - python >=3.9
    - python-crontab
    - pyyaml
    - setuptools >=30.3.0
    - windrose >=1.6.8
    - wrf-python >=1.3.1
    - openpyxl
    - xarray

test:
  imports:
    - wrftamer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://wrftamer.readthedocs.io/en/latest/
  summary: A python package to help you mangaging WRF projects and experiments
  license: MIT
  license_file:
    - LICENCE
    - LICENCES.third_party
  doc_url: https://wrftamer.readthedocs.io/
  dev_url: https://github.com/os-simopt/wrftamer

extra:
  recipe-maintainers:
    - 99740179
