{% set name = "wrftamer" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wrftamer-{{ version }}.tar.gz
  sha256: f3fc765623f1d1c7d9e8d4d32ae07a95e4e3a85c6b329a664a95c0b43ba367b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - cartopy >=0.18.0
    - click
    - holoviews
    - hvplot
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas >=1.3.5
    - panel
    - python >=3.9
    - python-crontab
    - pyyaml
    - setuptools >=30.3.0
    - shapely >=1.7.1
    - windrose >=1.6.8
    - wrf-python >=1.3.1
    - xarray

test:
  imports:
    - wrftamer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://wrftamer.readthedocs.io/en/latest/
  summary: A python package to help you mangaging WRF projects and experiments
  license: MIT
  license_file:
    - LICENCE
    - LICENCES.third_party
  doc_url: https://wrftamer.readthedocs.io/
  dev_url: https://github.com/os-simopt/wrftamer

extra:
  recipe-maintainers:
    - 99740179
