site_name: WRFtamer
site_url: https://wrftamer.readthedocs.io/en/latest/
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Customizing WRFtamer: customizing.md
    - Command Line tools: command_line_tools.md
    - GUI: GUI.md
    - FAQ: faq.md
    - About: about.md
theme: readthedocs
