#!/usr/bin/bash

# Start the application on a website
# Question: can I generalize the path? would this work from everywhere?

GUI_PATH=$(python -c "from gui import gui_path; print(str(gui_path))")

panel serve "$GUI_PATH"/gui.py --port=5009 --show

