#!/usr/bin/bash

# Start the application on a website
# Question: can I generalize the path? would this work from everywhere?

SCRIPT_DIR=$(python -c "import wrftamer; print(wrftamer.__file__.split('__')[0])")

panel serve "$SCRIPT_DIR"/gui/gui.py --port=5009 --show