name: Tokentest

# Controls when the workflow will run
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  jobs:
    test:
        
    runs-on: ubuntu-latest
    steps:
    - name: test token
    - run:|
      curl https://x-access-token:${{ secrets.ANACONDA_TOKEN }}@api.github.com
