name: publish_conda

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 #2?
    - name: Fetch tags and show version
      run: |       
        git fetch --prune --unshallow --tags # checkout action does not get these
        git describe --tags --dirty --always
        python show_version.py    
    - name: publish-to-conda
      uses: fcakyon/conda-publish-action@v1.3
      with:
        subdir: 'conda-recipe'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'linux'
